# Generated by Django 4.1.2 on 2022-10-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.FloatField()),
                ('sabores', models.ManyToManyField(to='pizzaria.sabores')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(auto_now=True)),
                ('pizza', models.ForeignKey(default='Pizza deletada', on_delete=django.db.models.deletion.SET_DEFAULT, to='pizzaria.pizza')),
                ('user', models.ForeignKey(default='Cliente excluido', on_delete=django.db.models.deletion.SET_DEFAULT, to='autorizacao.cliente')),
            ],
        ),
    ]
