# Generated by Django 4.1.2 on 2022-12-27 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizacao', '0002_alter_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('volume', models.FloatField()),
                ('preco', models.FloatField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebidas', models.ManyToManyField(related_name='bebidas', to='pizzaria.bebida')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(null=True, upload_to='images/')),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Realizado'), ('P', 'Em preparo'), ('S', 'Saiu para entrega'), ('F', 'Finalizado'), ('C', 'Cancelado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massa', models.TextField(choices=[('F', 'Fina'), ('M', 'Média'), ('G', 'Grande'), ('I', 'Integral')], default='M', max_length=1)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaria.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='sabores',
            field=models.ManyToManyField(related_name='sabores', to='pizzaria.sabores'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizzaria.carrinho')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_pedido', to='pizzaria.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='autorizacao.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='pizzas',
            field=models.ManyToManyField(related_name='pizzas', to='pizzaria.pizzapedido'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizacao.cliente'),
        ),
    ]
