# Generated by Django 4.1.2 on 2022-10-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
