# Generated by Django 4.1.2 on 2022-12-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('R', 'Realizado'), ('P', 'Em preparo'), ('S', 'Saiu para entrega'), ('F', 'Finalizado'), ('C', 'Cancelado')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
