# Generated by Django 4.1.2 on 2022-10-31 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0003_alter_pizza_sabores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pizza',
            field=models.ForeignKey(default='Pizza deletada', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pizza', to='pizzaria.pizza'),
        ),
    ]
