# Generated by Django 4.1.2 on 2022-11-26 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0004_alter_pedido_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Realizado'), ('P', 'Em preparo'), ('S', 'Saiu para entrega'), ('F', 'Finalizado'), ('C', 'Cancelado')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='pizzaria.status'),
        ),
    ]
