# Generated by Django 4.1.2 on 2022-12-10 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0001_initial'),
        ('pizzaria', '0005_status_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='imagem',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_pedido', to='pizzaria.status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(default='Cliente excluido', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_name', to='autorizacao.cliente'),
        ),
    ]
