# Generated by Django 4.1.2 on 2022-12-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0006_pizza_imagem_alter_pedido_status_alter_pedido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='borda',
            field=models.TextField(choices=[('F', 'Fina'), ('M', 'Média'), ('G', 'Grande'), ('I', 'Integral')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='sabores',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
